# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0002_auto_20170621_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='address',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='long',
            new_name='lng',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='name',
            new_name='shop_name',
        ),
        migrations.AddField(
            model_name='shop',
            name='address2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='address3',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='address4',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
