# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0003_auto_20170624_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='hpg_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='ret_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='tab_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
