# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0006_auto_20170624_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='lat',
            field=models.DecimalField(decimal_places=13, max_digits=16),
        ),
        migrations.AlterField(
            model_name='shop',
            name='lng',
            field=models.DecimalField(decimal_places=13, max_digits=16),
        ),
    ]
