# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0007_auto_20170624_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oaiso_shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.BigIntegerField(blank=True, null=True)),
                ('shop_name', models.TextField()),
                ('budget_min', models.IntegerField(blank=True, null=True)),
                ('budget_max', models.IntegerField(blank=True, null=True)),
                ('review', models.TextField()),
                ('tel', models.BigIntegerField(blank=True, null=True)),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('address3', models.TextField()),
                ('address4', models.TextField()),
                ('lat', models.DecimalField(decimal_places=13, max_digits=16)),
                ('lng', models.DecimalField(decimal_places=13, max_digits=16)),
            ],
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
