# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0008_auto_20170627_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.BigIntegerField(blank=True, null=True)),
                ('shop_id', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.BigIntegerField(blank=True, null=True)),
                ('genre_name', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Oaiso_shop',
            new_name='Shop',
        ),
    ]
