# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0009_auto_20170627_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='genre_id',
        ),
        migrations.RemoveField(
            model_name='genre_name',
            name='genre_id',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='shop_id',
        ),
    ]
