# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0010_auto_20170627_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
