# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0012_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_source',
            fields=[
                ('shop_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tab_id', models.BigIntegerField(blank=True, null=True)),
                ('ret_id', models.BigIntegerField(blank=True, null=True)),
                ('hpg_id', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genreship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Genre_name',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='id',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='shop_id',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='id',
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_id',
            field=models.BigIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_name',
            field=models.TextField(default='DUMMY'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_id',
            field=models.BigIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_id',
            field=models.BigIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='shop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oaiso.Shop'),
        ),
        migrations.AddField(
            model_name='genreship',
            name='genre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oaiso.Genre'),
        ),
        migrations.AddField(
            model_name='genreship',
            name='shop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oaiso.Shop'),
        ),
        migrations.AddField(
            model_name='genre',
            name='shop_genre',
            field=models.ManyToManyField(through='oaiso.Genreship', to='oaiso.Shop'),
        ),
    ]
