# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0013_auto_20170628_1433'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data_source',
        ),
    ]
