# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0013_auto_20170628_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='hpg_id',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='ret_id',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='tab_id',
        ),
    ]
