# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0014_auto_20170629_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='hpg_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
