# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 05:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0015_shop_hpg_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
