# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0017_auto_20170628_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='shop_id',
            new_name='id',
        ),
    ]
