# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0018_auto_20170628_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='genre_id',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photo_id',
        ),
        migrations.AddField(
            model_name='genre',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
