# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0021_remove_genre_shop_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genreship',
            name='genre_id',
        ),
        migrations.RemoveField(
            model_name='genreship',
            name='shop_id',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Genreship',
        ),
    ]
