# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0023_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genreship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oaiso.Genre')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oaiso.Shop')),
            ],
        ),
    ]
