# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0025_auto_20170628_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genreship',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='genreship',
            name='shop',
        ),
        migrations.AlterField(
            model_name='genre',
            name='shop_genre',
            field=models.ManyToManyField(to='oaiso.Shop'),
        ),
        migrations.DeleteModel(
            name='Genreship',
        ),
    ]
