# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0026_auto_20170628_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genreship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='genre',
            name='shop_genre',
            field=models.ManyToManyField(through='oaiso.Genreship', to='oaiso.Shop'),
        ),
        migrations.AddField(
            model_name='genreship',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oaiso.Genre'),
        ),
        migrations.AddField(
            model_name='genreship',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oaiso.Shop'),
        ),
    ]
