# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 03:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0027_auto_20170629_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='shop_genre',
        ),
    ]
