# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0028_remove_genre_shop_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oaiso.Genre')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oaiso.Shop')),
            ],
        ),
        migrations.RemoveField(
            model_name='genreship',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='genreship',
            name='shop',
        ),
        migrations.DeleteModel(
            name='Genreship',
        ),
        migrations.AddField(
            model_name='genre',
            name='shop_relation',
            field=models.ManyToManyField(through='oaiso.Relationship', to='oaiso.Shop'),
        ),
    ]
