# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 04:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0030_auto_20170629_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='shop_relation',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='shop',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
