# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 01:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0032_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop',
            new_name='Shops',
        ),
    ]
