# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0033_auto_20170701_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.TextField()),
                ('budget_min', models.IntegerField(blank=True, null=True)),
                ('budget_max', models.IntegerField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('tel', models.BigIntegerField(blank=True, null=True)),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('address3', models.TextField()),
                ('address4', models.TextField()),
                ('lat', models.DecimalField(decimal_places=13, max_digits=16)),
                ('lng', models.DecimalField(decimal_places=13, max_digits=16)),
            ],
        ),
        migrations.AlterField(
            model_name='photo',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oaiso.Shop'),
        ),
        migrations.DeleteModel(
            name='Shops',
        ),
    ]
