# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0035_auto_20170701_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='shop_id',
        ),
        migrations.AddField(
            model_name='shop',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
