# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0036_auto_20170701_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
