# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 03:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0037_auto_20170701_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='shop',
            new_name='shop_id',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='id',
            new_name='shop_id',
        ),
    ]
