# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0038_auto_20170701_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_id',
            field=models.BigIntegerField(),
        ),
    ]
