# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0041_auto_20170702_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.TextField()),
                ('shop_relation', models.ManyToManyField(to='oaiso.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oaiso.Genre')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oaiso.Shop')),
            ],
        ),
    ]
