# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0042_genre_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='shop',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
