# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0043_auto_20170702_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_id', models.BigIntegerField(blank=True, null=True)),
                ('ret_id', models.BigIntegerField(blank=True, null=True)),
                ('hpg_id', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
