# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0044_data_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='address1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='tel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
