# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0045_auto_20170704_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='tel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
