# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0048_auto_20170704_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='tel',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
