# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0051_auto_20170704_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='shop_relation',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
