# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0052_auto_20170704_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.TextField(blank=True, null=True)),
                ('shop_relation', models.ManyToManyField(to='oaiso.Shop')),
            ],
        ),
    ]
