# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0016_delete_genre'),
        ('oaiso', '0053_genre'),
    ]

    operations = [
    ]
