# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0055_auto_20170704_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='budget_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='budget_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
