# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0057_auto_20170904_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='budget_dinner',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='budget_lunch',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=13, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=13, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='shop_test',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=13, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='shop_test',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=13, max_digits=16, null=True),
        ),
    ]
