# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-12 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0058_auto_20170905_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='budget_dinner_min',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='budget_lunch_min',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
