# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-12 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0059_auto_20171012_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='genre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Data_source',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='shop_relation',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='address3',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='address4',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='budget_1',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='budget_dinner',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='budget_lunch',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='budget_max',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='budget_min',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='hpg_id',
        ),
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='budget_dinner_max',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='budget_lunch_max',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
