# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-13 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0060_auto_20171012_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_test',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop_test',
            name='budget_dinner_max',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop_test',
            name='budget_dinner_min',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop_test',
            name='budget_lunch_max',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop_test',
            name='budget_lunch_min',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop_test',
            name='genre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop_test',
            name='photo_food',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop_test',
            name='photo_shop',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop_test',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop_test',
            name='tel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
