# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-28 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaiso', '0063_auto_20171228_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_info',
            name='super_genre',
            field=models.TextField(blank=True, null=True),
        ),
    ]
